from PIL import Image, ImageFilter

img = Image.open("./Original/pikachu.jpg")
img2 = Image.open("./Original/astro.jpg")
filtered_img = img.filter(ImageFilter.BLUR)
filtered_img = img.filter(ImageFilter.SMOOTH)
filtered_img = img.filter(ImageFilter.SHARPEN)
filtered_img = img.convert("L")
rotated = filtered_img.rotate(90)
resize = filtered_img.resize((300, 300))
crop_dimenssions = (100, 100, 400, 400)
cropped = filtered_img.crop(crop_dimenssions)
img2.thumbnail((400, 400))
# filtered_img.show()
# rotated.show()
print(img.format)
print(img.size)
print(img.mode)
print(img2.size)
filtered_img.save("./Modified/blur.png", "png")
filtered_img.save("./Modified/smooth.png", "png")
filtered_img.save("./Modified/sharpen.png", "png")
filtered_img.save("./Modified/grey.png", "png")
rotated.save("./Modified/rotated.png", "png")
resize.save("./Modified/resized.png", "png")
cropped.save("./Modified/cropped.png", "png")
img2.save("./Modified/astro.png", "png")
